#!/bin/csh -f
#  $Id: fixPermissions_llnl,v 1.1 2009/11/19 23:44:45 dave Exp $
#  ---------------------------------------------------------------------
#  PURPOSE:  Set the permissions (if allowed).
#  CHANGES:
#  04/08/03 llc Check results in case not allowed to change directory.
#               In this case, allowed to change files in directory (by hand).
#  ---------------------------------------------------------------------


set VERSION = `python -c "import sys; print '%d.%d' % sys.version_info[:2]"`
set GIST = "lib/python${VERSION}/site-packages/gist"
set GISTPATH = ${GIST}.pth
echo ${GIST}
echo ${GISTPATH}

foreach entry (g include i i0 bin/gist ${GIST} ${GISTPATH})

   echo $entry

   echo "cd ${PYTHONHOME};chgrp -R pydev $entry"
   cd ${PYTHONHOME};chgrp -R pydev $entry 

   echo "cd ${PYTHONHOME};chmod -R g+rwX $entry"
   cd ${PYTHONHOME};chmod -R g+rwX $entry

   echo "cd ${PYTHONHOME};chmod -R o+rX $entry"
   cd ${PYTHONHOME};chmod -R o+rX $entry

end

#  .. Check results
echo " "
echo "ls -l ${PYTHONHOME}/${GIST}"
ls -l ${PYTHONHOME}/${GIST}

