#!/bin/csh -f 
#
#  -------------------------------------------------------------------
#  NAME:     install
#  PURPOSE:  For personal installs.
#  CHANGES:
#  11/08/04 llc Install --x11 version of LLNL Mac OSX machines.
#  03/03/08 dpg Uses setup.py config instead of make config.
#  -------------------------------------------------------------------


#  Generic installations:

#  Not required
#if ! $?PYTHONHOME then
#   echo "*** First define PYTHONHOME"
#   exit
#endif

#echo "cd src; make clean; make config; cd .."
#cd src; make clean; make config; cd .. 

echo "touch src/*.c src/play/*/*"
touch src/*.c src/play/*/*
#echo "rm -rf build"
#rm -rf build

set sys = `uname`
if $sys == "Darwin" then
   echo "python setup.py --x11 config"
   python setup.py --x11 config
   echo "python setup.py --x11 install"
   python setup.py --x11 install
else
   echo "python setup.py config"
   python setup.py config
   echo "python setup.py install"
   python setup.py install
endif

