#!/bin/csh -f 
#  $Id: llnl_install,v 1.1 2009/11/19 23:44:45 dave Exp $
#  ---------------------------------------------------------------------
#  
#  NAME:     llnl_install
#
#  PURPOSE:  Script to install pygist in the public python (/usr/apps/python)
#            on LLNL machines.
#
#  CHANGES:
#  04/07/03 llc Add tracker code usage collection.
#  11/08/04 llc Install --x11 version of LLNL Mac OSX machines.
#
#  ---------------------------------------------------------------------

if ! $?PYTHONHOME then
   echo "*** First define PYTHONHOME"
   exit
endif

echo "cd src; make clean; make config; cd .."
cd src; make clean; make config; cd .. 

#  .. Add tracker to gist/gist.py for the installation
#  .. Restore the original after installation.

echo "cp gist/gist.py gist/gist.save"
cp gist/gist.py gist/gist.save

echo "sed -f sed_llnl < gist/gist.py > gist/gist.new; mv -f gist/gist.new gist/gist.py"
sed -f sed_llnl < gist/gist.py > gist/gist.new; mv -f gist/gist.new gist/gist.py

echo "touch src/*.c src/play/*/*"
touch src/*.c src/play/*/*

set sys = `uname`
if $sys == "Darwin" then
   echo "python setup.py --x11 install"
   python setup.py --x11 install
else
   echo "python setup.py install"
   python setup.py install
endif

echo "cp gist/gist.save gist/gist.py"
cp gist/gist.save gist/gist.py

echo "fixPermissions_llnl"
fixPermissions_llnl
